export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REQUEST_FETCH_LOGIN = "REQUEST_FETCH_LOGIN";
export const ERROR = "ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const REQUEST_FETCH_REGIST = "REQUEST_FETCH_REGIST";
export const PROFILE_INIT = "PROFILE_INIT";

export default {
  LOGIN,
  LOGOUT,
  REQUEST_FETCH_LOGIN,
  ERROR,
  CLEAR_ERROR,
  REQUEST_FETCH_REGIST,
  PROFILE_INIT
};
